# Generated by Django 5.0.7 on 2024-07-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_secondrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='thirdRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='firstRow')),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'thirdRow',
                'verbose_name_plural': 'Üçüncü satırdaki resimler',
            },
        ),
    ]
